CREATE TABLE XX_TABLE_NAME_TN (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50)
);

CREATE TABLE YY_ANOTHER_TABLE_TN (
    ID NUMBER PRIMARY KEY,
    DESCRIPTION VARCHAR2(100)
);

CREATE TABLE EMP_TABLE_TN (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    SALARY NUMBER NOT NULL
);
